blank_issues_enabled: true
contact_links:
  - name: Chronnote website
    url: https://chronnote.top
    about: Visit the official Chronnote website.
  - name: Email
    url: mailto:1155181470@link.cuhk.edu.hk
    about: Contact the Chronnote team by email.
